### ISSUE TITLE
Add properties parameter to FormComponent->createElement() method

### ISSUE THREAD

**Issue by kftw** [tollwerk/TYPO3-ext-tw_componentlibrary#13]
A way to set additional form element properties comes in handy sometimes. Because the return value of the createElement() method is NULL (could fix that as well), I suggest a third parameter for the method to pass an array with custom properties like this:

*Classes/Component/FormComponent.php*

```php
    /**
     * Create a form element
     *
     * @param string $typeName Type of the new form element
     * @param string $identifier Form element identifier
     * @param array $properties Custom Properties for the form element
     * @return AbstractRenderable Renderable form element
     * @throws \TYPO3\CMS\Form\Domain\Exception\TypeDefinitionNotFoundException
     * @throws \TYPO3\CMS\Form\Domain\Exception\TypeDefinitionNotValidException
     */
    protected function createElement($typeName, $identifier = null, $properties = [])
    {
        $identifier = trim($identifier) ?:
            strtr(GeneralUtility::camelCaseToLowerCaseUnderscored($typeName), '_', '-').'-1';
        $this->element = $this->page->createElement($identifier, $typeName);
        $this->element->setProperty('fluidAdditionalAttributes', []);

        foreach($properties as $propertyName => $propertyValue){
            $this->element->setProperty($propertyName, $propertyValue);
        }

        return $this->element;
    }

```

**Comment by kftw** [comment]
The same should propably be possible for setting renderingOptions as well.

**Comment by jkphl** [comment]
@kftw In fact, the return value of the `createElement()` method isn't `NULL` (see your code example), so one can very well set the properties (and rendering options) on the returned element. In addition, the `element` property is set as well, so you could always refer to the element with `$this->element`. In order to avoid baking in a lot of validation into the `createElement()` method I'd prefer to let the components set the properties and renderingOptions themselves.
